# Generated by Django 3.2.13 on 2022-05-22 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DriveName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('production', models.IntegerField()),
                ('poster', models.ImageField(upload_to='Movie/Poster/')),
                ('review', models.TextField()),
                ('type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series')], max_length=10)),
                ('category', models.ManyToManyField(related_name='category_of_movies', to='mov.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('episode', models.IntegerField()),
                ('url', models.URLField()),
                ('resolution', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mov.drivename')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_of_series_url', to='mov.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('resolution', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mov.drivename')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_of_movie_url', to='mov.movie')),
            ],
        ),
    ]
