# Generated by Django 3.2.13 on 2022-05-22 17:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivename',
            name='icon',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='drive_icons/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MovieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_of_movie_image', to='mov.movie')),
            ],
        ),
    ]
