# Generated by Django 3.2.13 on 2022-05-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0003_auto_20220523_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=50),
        ),
    ]
