# Generated by Django 3.2.13 on 2022-05-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0004_alter_movie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, upload_to='Movie/Poster/'),
        ),
    ]
